### ISSUE TITLE
Please submit this egg to the C5 coop

### ISSUE THREAD

**Issue by wasamasa** [tenderlove/chicken-yaml#14]
It should be a matter of posting an email on chicken-users or a message on the `#chicken` channel with this link: https://raw.githubusercontent.com/tenderlove/chicken-yaml/master/yaml.release-info. Installation works on Arch and Ubuntu 20.04 despite the missing pkg-config support. I'll prepare a PR for that part later, based on my solution for https://depp.brause.cc/breadline.

**Comment by zilti** [comment]
Seconded, I am using this egg for a script at work, it would be nice to have it available that way :)

**Comment by wasamasa** [comment]
The custom build file is in https://github.com/tenderlove/chicken-yaml/pull/15 and the egg has been submitted to the coop, so I guess I can close this one.
