### ISSUE TITLE
Missing release-info entry for v0.1.3

### ISSUE THREAD

**Issue by sjamaan** [tenderlove/chicken-yaml#2]
Hi Aaron,

I noticed you've fixed https://bugs.call-cc.org/ticket/1208 in `v0.1.3`. However, the latest release that can be downloaded with chicken-install is `0.1.2`. Would you be so kind as to add a line for v0.1.3 to release-info?

**Comment by tenderlove** [comment]
Really sorry about that, it should be pushed now!
