### ISSUE TITLE
Performance issue with reasonably sized file

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [tenderlove/chicken-yaml#3]
I tried to load a "resonably sized" (imo) file with the following code:

    (time (yaml-load (open-input-file "data/hsk-1.yaml")))

Output:

    3.588s CPU time, 0.468s GC time (major), 11759453 mutations, 460/27347 GCs (major/minor)

This should not take so long. I have HSK 1 to 6 files, with increasing sizes to load. When I loaded the complete set of files, I first thought I had somehow caused an infinite loop to run.

The file is attached.
[hsk-1.yaml.txt](https://github.com/tenderlove/chicken-yaml/files/1032964/hsk-1.yaml.txt)

My CPU is `Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz`

**Comment by tenderlove** [comment]
Thanks for using my library!  Also thank you for the ticket.  I was able to reproduce the problem, and yes it's way too slow.  I'll try to figure out what's wrong, but I have to warn you I've never done perf work with Chicken, so it might take a while for me to figure out.

**Comment by tenderlove** [comment]
Looks like the bottleneck is in `parse-scalar`:

```
[aaron@TC yaml (master)]$ chicken-profile PROFILE.28349
reading `PROFILE.28349' ...

procedure                                                calls  seconds  average  percent
-----------------------------------------------------------------------------------------
yaml#parse-loop                                           2120    6.123    0.002  100.000
yaml#yaml-load                                               1    6.123    6.123  100.000
yaml#do-parse-input                                          1    6.123    6.123  100.000
yaml#yaml-parse                                              1    6.123    6.123  100.000
yaml#do-parse                                                1    6.123    6.123  100.000
yaml#handle-scalar-event                                  1810    6.099    0.003   99.608
yaml#parser-scalar                                        1810    6.075    0.003   99.232
yaml#parse-scalar                                         1802    6.069    0.003   99.118
yaml#pull-event                                           2120    0.006    0.000    0.097
yaml#handle-mapping-end-event                              152    0.006    0.000    0.097
yaml#parser-mapping-end                                    152    0.006    0.000    0.097
```

**Comment by tenderlove** [comment]
I was able to cut the time in half, though I'm still not happy with the performance.

**Comment by tenderlove** [comment]
I was able to get your sample program down to ~450ms:

```
[aaron@TC yaml (master)]$ ./test
0.445s CPU time, 0.041s GC time (major), 1073037/32975 mutations (total/tracked), 75/2134 GCs (major/minor) 
```

I can keep poking at it for speed improvements, but if this is good enough for you I can cut a release.  Thanks!

**Comment by tenderlove** [comment]
Sorry for the noise, I found one more easy win that brings it down to 8ms:

```
[aaron@TC yaml (master)]$ ./test
0.009s CPU time, 0.001s GC time (major), 8868/110 mutations (total/tracked), 1/41 GCs (major/minor)
```

**Comment by ZelphirKaltstahl** [comment]
@tenderlove Wow, so much going on here! Good to see this project and you are active. I did not know about `chicken-profile` and just started out with Chicken Scheme. I only used `(time ...)` so far.

Oh and sorry for having to name the file `.txt`. GitHub would not let me upload with `.yaml` ending.

I am not sure how you set up the test (for example the profile number thing: `PROFILE.28349`). Is there anything I should test on my end?

**Comment by ZelphirKaltstahl** [comment]
I updated the library on my machine and loaded the yaml files. Performance is fine now for my use case :+1:

**Comment by tenderlove** [comment]
@ZelphirKaltstahl Since I'm pretty new to profiling stuff with chicken, I'll put exactly the commands I used here (then I can google it later too! 😉).

In my checkout of the repository, I did this:

```
[aaron@TC yaml (master)]$ CSC_OPTIONS=-profile chicken-install
```

Which compiled the library with profiling enabled.  Then I compiled the test program with profiling enabled:

```
[aaron@TC yaml (master)]$ cat test.scm
(use yaml sql-null)

(time (yaml-load (open-input-file "/Users/aaron/Downloads/hsk-1.yaml.txt")))
[aaron@TC yaml (master)]$ csc -profile test.scm
```

Then I ran the compiled program, which generated a profile file (in addition to executing the code):

```
[aaron@TC yaml (master)]$ ./test
0.042s CPU time, 0.001s GC time (major), 138023/126582 mutations (total/tracked), 1/92 GCs (major/minor)
[aaron@TC yaml (master)]$ ls PROFILE.38517 
```

Then I ran `chicken-profile` against the resulting file:

```
[aaron@TC yaml (master)]$ chicken-profile PROFILE.38517 
reading `PROFILE.38517' ...

procedure                                                calls  seconds  average  percent
-----------------------------------------------------------------------------------------
yaml#yaml-parse                                              1    0.042    0.042  100.000
yaml#yaml-load                                               1    0.042    0.042  100.000
yaml#parse-loop                                           2120    0.041    0.000   97.619
yaml#do-parse-input                                          1    0.041    0.041   97.619
yaml#do-parse                                                1    0.041    0.041   97.619
yaml#handle-scalar-event                                  1810    0.029    0.000   69.047
yaml#parser-scalar                                        1810    0.012    0.000   28.571
yaml#parse-scalar                                         1802    0.008    0.000   19.047
```

These numbers are against `master`.

> Is there anything I should test on my end?

I don't think so.  Unless you want to try this out! 😊

> Performance is fine now for my use case

Great.  I'll close the ticket.  Thanks for reporting this!
