### ISSUE TITLE
Broken Build Without pkg-config

### ISSUE THREAD

**Issue by Petruchio** [tenderlove/chicken-yaml#5]
I kept getting an error with this egg, on a basic test case:

```
csi -R yaml -e '(use yaml)(yaml-load "--- foo")'
csi: symbol lookup error: /var/lib//chicken/8/yaml.so: undefined symbol: yaml_parser_initialize
```
Someone in #chicken on Freenode was helpful enough to test, and he didn't get the same error.  Turns out to have been related to an error message during installation:

`sh: 1: pkg-config: not found`

Installing pkg-config and re-installing the egg fixed this.  I would suggest changing the installation to check for pkg-config, and having the process fail with a helpful message if it's not available.

**Comment by tenderlove** [comment]
Ah makes sense.  I'll add a check for `pkg-config`. Thanks for reporting this!

**Comment by wasamasa** [comment]
This seems to have been reported for C4 as the C5 version just hardcodes the flags. You'd have the same issue though as soon as you use a custom build file for C5.
