### ISSUE TITLE
Release for chicken 5.0 and error in .egg

### ISSUE THREAD

**Issue by dieggsy** [tenderlove/chicken-yaml#6]
There seems to be a bug in the .egg file: In Chicken 5 irregex is not an egg and comes with chicken scheme (see here: https://wiki.call-cc.org/man/5/Included%20modules). 

Also, the egg is not installable with `chicken-install yaml` for C5 - can we get a release published for Chicken 5?

**Comment by masukomi** [comment]
re the release for chicken 5 I submitted it but received this feedback:

Thanks.  There are some issues with the new version:

* srfi-1 is an egg in CHICKEN 5, so it must be in `test-dependencies` in
  the .egg file.

* tests/run.scm works only in CHICKEN 5, but apparently the repo is
  supposed to handle both CHICKEN 4 and 5.  Tests for CHICKEN 4 are
  going to fail as soon as version 0.2.1 hits the repository of eggs.

**Comment by wasamasa** [comment]
Closed by the linked merge request and #10.
